services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/fpm/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: laravel-test
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - ${UID:-1000}
      - ${GID:-1000}
    volumes:
      -  ./api:/app
    ports:
      - "9000:9000"
    networks:
      - app-test

  vue-app:
    build:
      context: .
      dockerfile: ./docker/npm/Dockerfile
    ports:
      - "5173:5173"
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - ${UID:-1000}
      - ${GID:-1000}
    volumes:
      - ./vue:/app
    networks:
      - app-test

  php-cli:
    build:
      context: .
      dockerfile: ./docker/php/cli/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - ${UID:-1000}
      - ${GID:-1000}
    volumes:
      - ./api:/app
    networks:
      - app-test

  proxy:
    image: nginx:latest
    volumes:
      - ./api/public:/app/public
      - ./docker/proxy/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-test
    ports:
      - "80:80"

  db:
    image: mysql:8.0
    container_name: laravel-vue-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-test

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8001:80
    environment:
      PMA_HOSTS: 'db'
      MAX_EXECUTION_TIME: -1
      MEMORY_LIMIT: -1
      UPLOAD_LIMIT: -1
    networks:
      - app-test

volumes:
  db-data:

networks:
  app-test: